package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    Cart selectCartByUseridAndProductid(@Param("userId")Integer userId,
                                        @Param("productId")Integer productId);
    List<Cart> selectCarByUserid(Integer userId);
    /**
     * 是否全选
     * */
    int isCheckAll(Integer userId);
    int deleteByUserIdAndProductIds(@Param("userId") Integer userId,
                                    @Param("productIdList") List<Integer> productIdList);
    /**
     * 操作购物车商品是否被选中
     * */
    int selectOrUnselectProduct(@Param("productId") Integer productId,
                                @Param("userId") Integer userId,
                                @Param("check") Integer check);

    int getCartProductCount(@Param("userId") Integer userId);

    List<Cart> findCartByUserIdAndChecked(@Param("userId") Integer userId);

    /**
     * 批量删除
     * */
    int deleteBatch(List<Cart>cartList);
}