package com.neuedu.dao;

import com.neuedu.pojo.Shipping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    Shipping selectByPrimaryKey(@Param("shippingId") Integer shippingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shipping record);

    int delByUserIdandShippingId(@Param("shippingId") Integer shippingId,
                                 @Param("userId") Integer userId);

    int updateBySelectKey(@Param("shipping") Shipping shipping,
                          @Param("userid")Integer userid);

    List<Shipping> selectAllShipping(@Param("userId") Integer userId);
    Shipping findShippingByShippingIdAndUsserId(@Param("shippingId") Integer shippingId,
                                                @Param("userId") Integer userId);
}