package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(@Param("userInfo") UserInfo record);


    int exsitsUsername(@Param("username") String username);
    int exsitsEmail(@Param("email")String email);
    UserInfo findByUsernameAndPassword(@Param("user") UserInfo userInfo);
    UserInfo findUser(@Param("username") String username, @Param("password") String password);
    String selectQuestionByUsername(@Param("username") String username);
    int selectByUsernameAndQuestionAndAnswer(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);
    int updateUserPassword(@Param("username") String username,@Param("password") String newPassword);
    int exsitsPassword(@Param("username") String username,@Param("password")String passwordOld);
}